baseurl = "https://e74000.net/"
languageCode = "en-gb"
theme = "e74000"
title = "e74000"

[markup.goldmark.renderer]
    unsafe= true

[markup]
    [markup.highlight]
        anchorLineNos = false
        codeFences = true
        guessSyntax = false
        hl_Lines = ''
        hl_inline = false
        lineAnchors = ''
        lineNoStart = 1
        lineNos = false
        lineNumbersInTable = true
        noClasses = true
        noHl = false
        style = 'swapoff'
        tabWidth = 4